server:
  port: 8084

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/plantation_db
    username: postgres
    password: password # TODO: Change this or use env var
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
