server:
  port: 8082

spring:
  application:
    name: operations-service
  datasource:
    url: jdbc:postgresql://localhost:5432/plantation_db
    username: postgres
    password: superman9
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
